-- schema database
CREATE TABLE folder (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `level` TINYINT UNSIGNED NOT NULL,
  `pid` CHAR(36) NOT NULL,
  `name` NVARCHAR(128) NOT NULL,
  `note_num` SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE note_schema ( 
  `nid` CHAR(36) PRIMARY KEY NOT NULL,
  `fid` CHAR(36) NOT NULL,
  `title` NVARCHAR(140) NOT NULL,
)

CREATE TABLE tag_meta (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `name` NVARCHAR(32) NOT NULL,
)

CREATE TABLE tag (
  `nid` CHAR(36) NOT NULL,
  `title` NVARCHAR(140) NOT NULL,
  `tid` CHAR(36)  NOT NULL,
)

CREATE  TABLE star (
  `nid` CHAR(36) PRIMARY KEY NOT NULL,
  `title` NVARCHAR(140) NOT NULL,
)

CREATE TABLE blog (
  `nid` CHAR(36) PRIMARY KEY NOT NULL,
  `title` NVARCHAR(140) NOT NULL,
)

CREATE TABLE user (

)


-- note database
CREATE TABLE note (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `type` CHAR(1) NOT NULL,    -- 'O' 'M' 'R'
  `title` NVARCHAR(140) NOT NULL,
  `c_time` DATETIME NOT NULL,
  `u_time` DATETIME NOT NULL,
  `word_count` INT UNSIGNED NOT NULL,
  `author` NVARCHAR(28) DEFAULT NULL,
  `link` VARCHAR(255) DEFAULT NULL,
  `lisence` VARCHAR(16) DEFAULT NULL,
  `remark` NVARCHAR(800) DEFAULT NULL,
  `content` TEXT NOT NULL,
  `version` INT UNSIGNED NOT NULL
)