/**
 * Anynote release matrix: the single source of truth for independently versioned
 * release units and the formats they exchange.
 *
 * Design §19.2 requires Desktop, Worker, SDK, and first-party plugins to release independently, with explicit cross-version
 * compatibility windows. This module converges those facts into an executable contract: it only describes versions and compatibility,
 * performs no I/O, and depends on no Node, Electron, storage, or UI, so the desktop main process, Worker,
 * and release tooling can read the same definition.
 *
 * Maintenance conventions:
 * - `releaseUnits[].version` must equal the `version` in the corresponding package.json.
 * - `releaseUnits[].contract` must equal the contract constant exported from the code (e.g.
 *   `apiContractVersion`）。
 * - `releaseFormats[].version` must equal the version written by each format's zod schema / table schema.
 * - Once declared, a compatibility window is a promise to legacy consumers; `legacyConsumers` pins the old call-surface
 *   fixtures that must keep passing.
 *
 * `tests/release-matrix.test.mjs` compares the above conventions item by item against the real code.
 */

/** A component that is independently versioned and released. */
export type ReleaseUnitId =
  | "desktop"
  | "worker"
  | "sdk"
  | "devtools"
  | "first-party"
  | "format";

/** An interface negotiated across units (file format, protocol, or database schema). */
export type FormatId =
  | "notebook-schema"
  | "notebook-archive"
  | "logical-protocol"
  | "local-backup"
  | "cloud-backup-head"
  | "cloud-backup-manifest"
  | "extension-package"
  | "extension-directory"
  | "extension-settings";

/** Delivery channel of a unit. */
export type ReleaseChannel =
  | "npm"
  | "github-release"
  | "cloudflare-deploy"
  | "internal";

/** An ESM/type entry point a unit exposes. */
export interface ReleaseEntrypoint {
  /** Subpath export relative to the package root, e.g. `.` or `./packages/extension-tools/cli.js`. */
  readonly subpath: string;
  /** Type declaration file; may be omitted for a pure CLI entry. */
  readonly types?: string;
  /** ESM runtime entry. */
  readonly import: string;
}

export interface ReleaseUnit {
  readonly id: ReleaseUnitId;
  /** npm package name; the desktop app keeps its application identifier. */
  readonly package: string;
  /** Independent version of the unit, equal to its package.json version. */
  readonly version: string;
  /** Independent contract version of the public surface; omitted for units with no surface. */
  readonly contract?: number;
  /** Runtime requirements published to consumers (the real engine, without custom fields). */
  readonly engines: Readonly<Record<string, string>>;
  /** SPDX identifier; uses `SEE LICENSE IN LICENSE` until a license is chosen. */
  readonly license: string;
  readonly channel: ReleaseChannel;
  /** Whether an installable npm tarball is produced. */
  readonly publishable: boolean;
  /** ESM/type entries packaged into the artifact. */
  readonly entrypoints: readonly ReleaseEntrypoint[];
  /** Executable mapping declared by a CLI unit. */
  readonly bin?: Readonly<Record<string, string>>;
  /** One-line description in the release manifest and docs. */
  readonly description: string;
}

export interface ReleaseFormat {
  readonly id: FormatId;
  /** File/table identifier; an empty string when there is no string identifier. */
  readonly tag: string;
  /** Integer format version currently written by the code. */
  readonly version: number;
  /** The unit that defines and evolves this format. */
  readonly owner: ReleaseUnitId;
}

export interface CompatibilityWindow {
  /** The unit that consumes the interface. */
  readonly consumer: ReleaseUnitId;
  /** The unit or format that provides the interface. */
  readonly provider: ReleaseUnitId | FormatId;
  /** Units use a semver range, formats an integer range (e.g. `<=2`). */
  readonly accepts: string;
  readonly note: string;
}

/** Consumer fixtures that pin old public surfaces, continuously verifying forward compatibility. */
export interface LegacyConsumer {
  /** The unit public surface the fixture pins. */
  readonly units: readonly ReleaseUnitId[];
  /** Contract version at fixture authoring time, indexed by unit id. */
  readonly contracts: Readonly<Record<string, number>>;
  /** Repo-relative directory. */
  readonly fixture: string;
}

/** Version identifier of the matrix data itself. */
export const releaseMatrixFormat = "anynote.release-matrix.v1";

/**
 * Version identifier of the release manifest (a build artifact).
 * Generated by `scripts/build-release-matrix.mjs`, consumed by `scripts/release-matrix-smoke.mjs`.
 */
export const releaseManifestFormat = "anynote.release-manifest.v1";

/** SPDX license identifier used uniformly by all units; see the repo-root LICENSE for the text. */
export const releaseLicense = "MIT";

/**
 * Independent versions and delivery channels of the component units. The desktop version follows the root package.json (`release.yml`
 * also validates the tag against it), and the other units follow their own package.json.
 */
const unitList: readonly ReleaseUnit[] = [
  {
    id: "desktop",
    package: "@anynote/desktop",
    version: "0.1.0",
    engines: { node: ">=24.0.0", electron: "41.9.1" },
    license: releaseLicense,
    channel: "github-release",
    publishable: false,
    entrypoints: [],
    description: "Electron 桌面应用（Main / Preload / Renderer）",
  },
  {
    id: "worker",
    package: "@anynote/cloudflare-backup",
    version: "0.1.0",
    engines: { node: ">=24.0.0" },
    license: releaseLicense,
    channel: "cloudflare-deploy",
    publishable: false,
    entrypoints: [],
    description: "Cloudflare Worker + D1 + R2 逻辑备份服务",
  },
  {
    id: "sdk",
    package: "@anynote/plugin-sdk",
    version: "0.1.0",
    contract: 1,
    engines: { node: ">=24.0.0" },
    license: releaseLicense,
    channel: "npm",
    publishable: true,
    entrypoints: [
      { subpath: ".", types: "./index.d.ts", import: "./index.js" },
    ],
    description: "插件公共 API、声明式扩展与本地备份契约",
  },
  {
    id: "devtools",
    package: "@anynote/extension-tools",
    version: "0.1.0",
    engines: { node: ">=24.0.0" },
    license: releaseLicense,
    channel: "npm",
    publishable: true,
    entrypoints: [
      {
        subpath: "./packages/extension-tools/cli.js",
        types: "./packages/extension-tools/cli.d.ts",
        import: "./packages/extension-tools/cli.js",
      },
    ],
    bin: { "anynote-extension": "./packages/extension-tools/cli.js" },
    description: "扩展脚手架、清单校验与隔离试运行 CLI",
  },
  {
    id: "first-party",
    package: "@anynote/first-party-adapters",
    version: "0.1.0",
    contract: 1,
    engines: { node: ">=24.0.0" },
    license: releaseLicense,
    channel: "npm",
    publishable: true,
    entrypoints: [
      { subpath: ".", types: "./index.d.ts", import: "./index.js" },
    ],
    description: "白板、视频、导入与本地备份的首方可移植适配器",
  },
  {
    id: "format",
    package: "@anynote/protocol",
    version: "0.1.0",
    engines: {},
    license: releaseLicense,
    channel: "internal",
    publishable: false,
    entrypoints: [],
    description: "Notebook schema、归档、逻辑备份与扩展文件格式",
  },
];
export const releaseUnits: readonly ReleaseUnit[] = Object.freeze(unitList);

/** Format versions that must be negotiated across units. */
const formatList: readonly ReleaseFormat[] = [
  {
    id: "notebook-schema",
    tag: "notebook.sqlite",
    version: 2,
    owner: "format",
  },
  {
    id: "notebook-archive",
    tag: "anynote.notebook",
    version: 1,
    owner: "format",
  },
  {
    id: "logical-protocol",
    tag: "anynote.logical",
    version: 1,
    owner: "format",
  },
  {
    id: "local-backup",
    tag: "anynote.local-backup",
    version: 1,
    owner: "format",
  },
  {
    id: "cloud-backup-head",
    tag: "anynote.cloud-backup-head",
    version: 1,
    owner: "format",
  },
  {
    id: "cloud-backup-manifest",
    tag: "anynote.cloud-backup-manifest",
    version: 1,
    owner: "format",
  },
  {
    id: "extension-package",
    tag: "anynote.extension",
    version: 1,
    owner: "format",
  },
  {
    id: "extension-directory",
    tag: "anynote.extension-directory",
    version: 1,
    owner: "format",
  },
  {
    id: "extension-settings",
    tag: "anynote.extension-settings",
    version: 1,
    owner: "format",
  },
];
export const releaseFormats: readonly ReleaseFormat[] =
  Object.freeze(formatList);

/**
 * Compatibility window. `accepts` expresses "which provider version range a consumer accepts":
 * - Units use a semver range (`*`, exact, `^`, `~`, `>=`/`<=`/`>`/`<` are supported).
 * - Formats use an integer range (exact or `<=`/`>=`/`<`/`>`).
 * Design §19.2 requires an explicit rejection when incompatible, not a silent downgraded write.
 */
const windowList: readonly CompatibilityWindow[] = [
  {
    consumer: "desktop",
    provider: "notebook-schema",
    accepts: "<=2",
    note: "桌面可读写 schema 1（先迁移）与 2；更高 schema 明确拒绝",
  },
  {
    consumer: "desktop",
    provider: "notebook-archive",
    accepts: "1",
    note: "完整归档 anynote.notebook v1",
  },
  {
    consumer: "desktop",
    provider: "logical-protocol",
    accepts: "1",
    note: "与 Worker 仅在同一逻辑备份协议版本内互操作",
  },
  {
    consumer: "worker",
    provider: "logical-protocol",
    accepts: "1",
    note: "Worker 只接受 anynote.logical v1 请求",
  },
  {
    consumer: "desktop",
    provider: "sdk",
    accepts: "^0.1.0",
    note: "桌面宿主实现 SDK 0.1 契约（apiContractVersion 1）",
  },
  {
    consumer: "first-party",
    provider: "sdk",
    accepts: "^0.1.0",
    note: "首方适配器只使用 SDK 0.1 的公开导出",
  },
  {
    consumer: "desktop",
    provider: "extension-package",
    accepts: "1",
    note: "签名扩展包 anynote.extension.v1",
  },
  {
    consumer: "desktop",
    provider: "extension-directory",
    accepts: "1",
    note: "扩展目录 anynote.extension-directory.v1",
  },
  {
    consumer: "desktop",
    provider: "extension-settings",
    accepts: "1",
    note: "扩展设置 anynote.extension-settings.v1",
  },
  {
    consumer: "desktop",
    provider: "local-backup",
    accepts: "1",
    note: "本地磁盘备份清单 anynote.local-backup v1",
  },
  {
    consumer: "desktop",
    provider: "cloud-backup-head",
    accepts: "1",
    note: "云盘备份当前指针 anynote.cloud-backup-head v1",
  },
  {
    consumer: "desktop",
    provider: "cloud-backup-manifest",
    accepts: "1",
    note: "云盘备份完整清单 anynote.cloud-backup-manifest v1",
  },
];
export const compatibilityWindows: readonly CompatibilityWindow[] =
  Object.freeze(windowList);

/**
 * Legacy-consumer fixture list. The first version has no prior release, so this fixture is the 0.1 consumer;
 * later versions must keep passing unless the compatibility window is explicitly raised in the matrix and the fixture updated.
 */
const legacyList: readonly LegacyConsumer[] = [
  {
    units: ["sdk", "first-party"],
    contracts: { sdk: 1, "first-party": 1 },
    fixture: "tests/fixtures/legacy-consumer",
  },
];
export const legacyConsumers: readonly LegacyConsumer[] =
  Object.freeze(legacyList);

const unitById = new Map<ReleaseUnitId, ReleaseUnit>(
  releaseUnits.map((unit) => [unit.id, unit]),
);
const formatById = new Map<FormatId, ReleaseFormat>(
  releaseFormats.map((format) => [format.id, format]),
);

/** Whether it is a format id (rather than a unit id). */
export function isFormatId(value: string): value is FormatId {
  return formatById.has(value as FormatId);
}

export function getReleaseUnit(id: ReleaseUnitId): ReleaseUnit {
  const unit = unitById.get(id);
  if (!unit) throw Error(`未知发布单元: ${id}`);
  return unit;
}

export function getReleaseFormat(id: FormatId): ReleaseFormat {
  const format = formatById.get(id);
  if (!format) throw Error(`未知发布格式: ${id}`);
  return format;
}

interface Semver {
  major: number;
  minor: number;
  patch: number;
}

const semverPattern = /^(\d+)\.(\d+)\.(\d+)$/;

function parseSemver(value: string): Semver | undefined {
  const match = semverPattern.exec(value.trim());
  return match
    ? {
        major: Number(match[1]),
        minor: Number(match[2]),
        patch: Number(match[3]),
      }
    : undefined;
}

function compareSemver(a: Semver, b: Semver): number {
  return a.major - b.major || a.minor - b.minor || a.patch - b.patch;
}

function upperBound(semver: Semver, operator: "caret" | "tilde"): Semver {
  if (operator === "tilde")
    return { major: semver.major, minor: semver.minor + 1, patch: 0 };
  if (semver.major > 0) return { major: semver.major + 1, minor: 0, patch: 0 };
  if (semver.minor > 0) return { major: 0, minor: semver.minor + 1, patch: 0 };
  return { major: 0, minor: 0, patch: semver.patch + 1 };
}

function satisfiesComparator(target: Semver, comparator: string): boolean {
  const token = comparator.trim();
  if (!token) return true;
  const match = /^(>=|<=|>|<|=|\^|~)?\s*(\d+\.\d+\.\d+)$/.exec(token);
  if (!match) return false;
  const bound = parseSemver(match[2]) as Semver;
  switch (match[1]) {
    case ">=":
      return compareSemver(target, bound) >= 0;
    case ">":
      return compareSemver(target, bound) > 0;
    case "<=":
      return compareSemver(target, bound) <= 0;
    case "<":
      return compareSemver(target, bound) < 0;
    case "^":
      return (
        compareSemver(target, bound) >= 0 &&
        compareSemver(target, upperBound(bound, "caret")) < 0
      );
    case "~":
      return (
        compareSemver(target, bound) >= 0 &&
        compareSemver(target, upperBound(bound, "tilde")) < 0
      );
    default:
      return compareSemver(target, bound) === 0;
  }
}

/** Determine whether a version falls within a semver range (subset supported: `*`, exact, `^`, `~`, comparators). */
export function satisfiesRange(version: string, range: string): boolean {
  const target = parseSemver(version);
  if (!target) return false;
  const normalized = range.trim();
  if (!normalized || normalized === "*") return true;
  return normalized
    .split(/[\s,]+/)
    .filter(Boolean)
    .every((comparator) => satisfiesComparator(target, comparator));
}

/** Determine whether an integer format version falls within a format range. */
export function satisfiesFormatRange(version: number, range: string): boolean {
  const match = /^(<=|>=|<|>|=)?\s*(\d+)$/.exec(range.trim());
  if (!Number.isInteger(version) || !match) return false;
  const bound = Number(match[2]);
  switch (match[1]) {
    case "<=":
      return version <= bound;
    case ">=":
      return version >= bound;
    case "<":
      return version < bound;
    case ">":
      return version > bound;
    default:
      return version === bound;
  }
}

export type CompatibilityVerdict =
  | { readonly compatible: true; readonly window: CompatibilityWindow }
  | { readonly compatible: false; readonly reason: string };

/**
 * Validate whether "consumer + provider + provider version" falls within the declared compatibility window.
 * Returns incompatible when the consumer does not declare the provider, following "reject explicitly when incompatible".
 */
export function checkReleaseCompatibility(
  consumer: ReleaseUnitId,
  provider: ReleaseUnitId | FormatId,
  version: string | number,
): CompatibilityVerdict {
  const window = compatibilityWindows.find(
    (candidate) =>
      candidate.consumer === consumer && candidate.provider === provider,
  );
  if (!window)
    return {
      compatible: false,
      reason: `${consumer} 未声明对 ${provider} 的兼容窗口`,
    };
  const accepted = isFormatId(provider)
    ? typeof version === "number" &&
      satisfiesFormatRange(version, window.accepts)
    : typeof version === "string" && satisfiesRange(version, window.accepts);
  return accepted
    ? { compatible: true, window }
    : {
        compatible: false,
        reason: `${consumer} 接受 ${provider} ${window.accepts}，当前 ${version} 超出兼容窗口`,
      };
}

/** Asserting version of `checkReleaseCompatibility`; throws when out of range. */
export function assertReleaseCompatibility(
  consumer: ReleaseUnitId,
  provider: ReleaseUnitId | FormatId,
  version: string | number,
): void {
  const verdict = checkReleaseCompatibility(consumer, provider, version);
  if (!verdict.compatible) throw Error(verdict.reason);
}

/** Return the current version string of a unit or format, for logging and validation. */
export function releaseVersion(id: ReleaseUnitId | FormatId): string {
  return isFormatId(id)
    ? String(getReleaseFormat(id).version)
    : getReleaseUnit(id).version;
}
