-- schema database
CREATE TABLE folder (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `pid` CHAR(36) NOT NULL,
  `level` TINYINT UNSIGNED NOT NULL,
  `name` NVARCHAR(128) NOT NULL,
  `locked` TINYINT UNSIGNED DEFAULT 0,
  `total` SMALLINT UNSIGNED  DEFAULT 0
);
CREATE TABLE configure {
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(32) UNIQUE NOT NULL,
  `value` VARCHAR(127) DEFAULT NULL
}
CREATE TABLE tag (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `name` NVARCHAR(32) NOT NULL
);

-- note database
CREATE TABLE note (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `title` NVARCHAR(140) DEFAULT NULL,
  `type` CHAR(1) NOT NULL,    -- 'R' 'M' 
  `c_time` DATETIME NOT NULL,
  `u_time` DATETIME NOT NULL,
  `weight` TIMESTAMP DEFAULT 0,
  `locked` TINYINT UNSIGNED NOT NULL,
  `author` NVARCHAR(28) DEFAULT NULL,
  `origin` VARCHAR(255) DEFAULT NULL,
  `lisence` VARCHAR(16) DEFAULT NULL,
  `remark` NVARCHAR(800) DEFAULT NULL,
  `content` TEXT DEFAULT NULL,
  `version` INT UNSIGNED DEFAULT 1
)
CREATE TABLE history (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `nid` CHAR(36) NOT NULL,
  `when` DATETIME NOT NULL,
  `content` TEXT NOT NULL
);

-- extend database
CREATE TABLE allnote (
  `nid` CHAR(36) PRIMARY KEY NOT NULL,
  `fid` CHAR(36) NOT NULL,
  `title` NVARCHAR(140) NOT NULL,
  `tids` VARCHAR(776) DEFAULT NULL,
  `star` TINYINT UNSIGNED DEFAULT 0
);
CREATE TABLE trash (
  `id` CHAR(36) PRIMARY KEY NOT NULL,
  `title` NVARCHAR(140) DEFAULT NULL,
  `type` CHAR(1) NOT NULL,    -- 'R' 'M' 
  `content` TEXT DEFAULT NULL,
  `when`  TIMESTAMP DEFAULT 0
);
